### PR TITLE
DM-47382: query consDB and EFD for AOS

### PR DESCRIPTION
**Pull request by suberlak**

### CODE REVIEW

**Comment by suberlak** [comment]
Executed notebook in https://rubin-obs.slack.com/files/U07QE7YLK96/F07V0KPFSHG/aos_dm-47382_consdb_for_aos.pdf

**Review by jbkalmbach — APPROVED** [review]
Thanks for adding this. Can you add a section at the end showing how to get Zernikes out of the EFD?

**Comment by jbkalmbach** [comment]
Also recommend showing how to get the dof from the EFD.

**Comment by suberlak** [comment]
Added the suggested examples to the notebook, the executed version https://rubin-obs.slack.com/files/U07QE7YLK96/F0800GCB2HL/tutorial_query_consdb_efd.pdf

**Pull request merged**
