### PR TITLE
WET-007:  Compare CWFS approaches with ComCam

### PR DESCRIPTION
**Pull request by suberlak**
First part of WET-007:  compare Danish vs TIE using OR4 LsstComCam

### CODE REVIEW

**Review by jbkalmbach — CHANGES_REQUESTED** [review]
I think our plan for this repository is to have notebooks that should focus less on the analysis of the simulated data compared to the simulated truth and just use the simulated data as a placeholder. Using this placeholder data to demonstrate that the steps work where the notebooks should focus on the steps in an analysis we can realistically run on on-sky data.

**Comment by suberlak** [comment]
<p>ok, so perhaps to fulfill that <a href="https://rubinobs.atlassian.net/browse/SITCOM-1149" target="_blank">https://rubinobs.atlassian.net/browse/SITCOM-1149</a> I can move that analysis (WET-001 simulation of lsstCam / comCam  100 states ) to a technote, and here  in <code>	ts_as_analysis</code> only leave part with <code>comCam</code> data from OR4 being compared between Danish and TIE (skipping the OPD comparison)?    </p>

---

 <a href='https://app.reviewnb.com/lsst-sitcom/ts_aos_analysis/pull/7/discussion/#comment-2433777611'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by suberlak** [comment]
<p>Ok I couldn't at the time because of JM's surgery being done on the central AOS repo... With the fix not yet ready I can copy the relevant part to ensure that <code>zernikes</code> is a <code>QTable</code> and rerun the analysis just for <code>comCam</code> OR4 data here</p><p>   </p>

---

 <a href='https://app.reviewnb.com/lsst-sitcom/ts_aos_analysis/pull/7/discussion/#comment-2433777637'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by jbkalmbach — APPROVED** [review]
Nice, thanks for the changes, this looks ready to go.

**Pull request merged**
